chore: disable other actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,56 +1,56 @@
-#name: Build & Test
-#
-#on:
-#  push:
-#    branches: [ "master" ]
+name: Build & Test
+
+on:
+  push:
+    branches: [ "master" ]
 #  pull_request:
 #    branches: [ "master" ]
-#
-#jobs:
-#  lint:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Set up Go
-#        uses: actions/setup-go@v3
-#        with:
-#          go-version: '1.18'
-#      - name: Do format
-#        run: |
-#          go install golang.org/x/tools/cmd/goimports@latest
-#          ./build.sh format
-#          git status
-#      - name: Check format
-#        run: |
-#          if [[ $(git status --porcelain) ]]; then
-#            echo "Error: Please format files via ./build.sh format first ";
-#            echo "Found not format files:"
-#            git status --porcelain
-#            exit 1;
-#          fi
-#
-#  build-ubuntu:
-#    runs-on: ubuntu-latest
-#    needs: [ lint ]
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Set up Go
-#        uses: actions/setup-go@v3
-#        with:
-#          go-version: '1.18'
-#
-#      - name: Test
-#        run: go test -v ./...
-#
-#  build-windows:
-#    needs: [ lint ]
-#    runs-on: windows-latest
-#    steps:
-#      - uses: actions/checkout@v4
-#      - name: Set up Go
-#        uses: actions/setup-go@v3
-#        with:
-#          go-version: '1.18'
-#
-#      - name: Test
-#        run: go test -v ./...
+
+jobs:
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.18'
+      - name: Do format
+        run: |
+          go install golang.org/x/tools/cmd/goimports@latest
+          ./build.sh format
+          git status
+      - name: Check format
+        run: |
+          if [[ $(git status --porcelain) ]]; then
+            echo "Error: Please format files via ./build.sh format first ";
+            echo "Found not format files:"
+            git status --porcelain
+            exit 1;
+          fi
+
+  build-ubuntu:
+    runs-on: ubuntu-latest
+    needs: [ lint ]
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.18'
+
+      - name: Test
+        run: go test -v ./...
+
+  build-windows:
+    needs: [ lint ]
+    runs-on: windows-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.18'
+
+      - name: Test
+        run: go test -v ./...
