action: format

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,31 +2,53 @@ name: Build & Test
 
 on:
   push:
-    branches: [ "master" ]
+    branches: [ "master", "format-action" ]
   pull_request:
     branches: [ "master" ]
 
 jobs:
-  build-ubuntu:
-    runs-on: ubuntu-latest
+  lint:
     steps:
       - uses: actions/checkout@v4
       - name: Set up Go
         uses: actions/setup-go@v3
         with:
-          go-version: '^1.16'
+          go-version: '1.16'
+      - name: Do format
+        run: |
+          go install golang.org/x/tools/cmd/goimports@latest
+          ./build.sh format 
+          git status
+      - name: Check format
+        run: |
+          if [[ $(git status --porcelain) ]]; then
+            echo "Error: Please format files ";
+            exit 1;
+          fi
+  
+
+  build-ubuntu:
+    runs-on: ubuntu-latest
+    needs: [ lint ]
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.16'
 
       - name: Test
         run: go test -v ./...
 
   build-windows:
+    needs: [ lint ]
     runs-on: windows-latest
     steps:
       - uses: actions/checkout@v4
       - name: Set up Go
         uses: actions/setup-go@v3
         with:
-          go-version: '^1.16'
+          go-version: '1.16'
 
       - name: Test
         run: go test -v ./...
